services:
  app:
    build: .
    container_name: url-lookup-app
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=urllookup
      - MONGO_COLLECTION_NAME=urls
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - ENV_NAME=${ENV_NAME:-local}
      - API_PORT=8000
      - LOG_LEVEL=${LOG_LEVEL}
      - RATE_LIMIT=10
      - RATE_LIMIT_WINDOW=60
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - ./src:/app/src
  mongo:
    image: mongo:6.0
    container_name: url-lookup-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
